version: '3'
services:
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    hostname : postgresdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mosahebe_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/docker-entrypoint-initdb.d
      - ./scripts/restore_script.sh:/docker-entrypoint-initdb.d/backup_restore.sh
      - ./scripts/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
       postgresdb:
          condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres_network:
    driver: bridge
